### ISSUE TITLE
No such property: log for class: grails.plugin.awssdk.s3.AmazonS3Service

### ISSUE THREAD

**Issue by didinj** [agorapulse/grails-aws-sdk-s3#2]
I'm using grails 3.1.9 and found this error while run-app.

`No such property: log for class: grails.plugin.awssdk.s3.AmazonS3Service. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
    at grails.plugin.springsecurity.rest.RestLogoutFilter.doFilter(RestLogoutFilter.groovy:80)
    at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestContextHolderExceptionTranslationFilter.groovy:64)
    at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53)
    at grails.plugin.springsecurity.rest.RestAuthenticationFilter.doFilter(RestAuthenticationFilter.groovy:143)
    at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
    at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: groovy.lang.MissingPropertyException: No such property: log for class: grails.plugin.awssdk.s3.AmazonS3Service
    at grails.plugin.awssdk.s3.AmazonS3Service.storeInputStream(AmazonS3Service.groovy:274)
    at grails.plugin.awssdk.s3.AmazonS3Service.storeMultipartFile(AmazonS3Service.groovy:360)
    at com.axamandiri.ProductInfoController.$tt__save(ProductInfoController.groovy:48)
    at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
    at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
    at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
    at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
    ... 9 common frames omitted`

Using this version of plugin org.grails.plugins:aws-sdk-s3:2.0.1

Thanks,
Didin

**Comment by benorama** [comment]
Since Grails 3.2.0, LoggingTransformer AST uses SLF4J (https://github.com/grails/grails-core/commit/dec43eea25ddee2fd5bdb98d8f4881cf1e7a1570), so I've added @Slf4j annotation to AmazonS3Service.
I've released 2.0.2, let me know if it solves your issue.
